#!/bin/bash

# Get the path of the selected file or folder
path=$(echo -n "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | head -n 1)

# Copy the path to the clipboard
echo -n "$path" | xclip -selection clipboard

# Display a notification to indicate that the path has been copied
zenity --notification --text="$path copied to clipboard"

